version: "3.9"

services:
  db:
    hostname: db-hub.docker
    container_name: postgres-local-docker
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
#      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      target: app-release
    container_name: backend
    ports:
#      - "9999:9999"
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      db:
        condition: service_healthy