#version: "3.9"

services:
  db:
    hostname: db-hub.docker
    container_name: postgres-local-docker
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
#      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  migrate:
    container_name: migrate-docker
    image: migrate/migrate:latest
    command: [
      "-path", "/migrations",
      "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOSTNAME}:${POSTGRES_DB_PORT}/${POSTGRES_DB}?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      db :
        condition: service_healthy
  backend:
    build:
      context: .
      target: builder
    container_name: backend
    environment:
      - "TZ=${TIMEZONE}"
    volumes:
      - "${LOG_PATH}:/app/logs"
    ports:
#      - "9999:9999"
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      db:
        condition: service_healthy